/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package main;

/**
 *
 * @author User
 */

import controller.AuthService;
import javax.swing.JOptionPane;
import utils.ValidationUtils;
import javax.swing.SwingWorker;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.GradientPaint;
import java.awt.Cursor;

public class ResetPasswordDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ResetPasswordDialog.class.getName());

    private final AuthService authService;
    String emailText;
    
    /**
     * Creates new form ResetPasswordDialog
     */
    public ResetPasswordDialog(java.awt.Frame parent, boolean modal, AuthService authService) {
        super(parent, modal);
        this.authService = authService;
        initComponents();
        setLocationRelativeTo(parent);
        setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
    }

    private void setLoading(boolean loading) {
        emailTxt.setEnabled(!loading);
        cancelBtn.setEnabled(!loading);
        resetBtn.setEnabled(!loading);
        setCursor(loading ? java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR) : java.awt.Cursor.getDefaultCursor());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        resetPasswordLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        resetBtn = new javax.swing.JButton() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();

                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // Warna dasar [0,121,121] → warna lebih gelap & terang untuk efek hover/press
                Color normalTop = new Color(0, 150, 150);
                Color normalBottom = new Color(0, 121, 121);

                Color hoverTop = new Color(0, 170, 170);
                Color hoverBottom = new Color(0, 145, 145);

                Color pressTop = new Color(0, 110, 110);
                Color pressBottom = new Color(0, 90, 90);

                GradientPaint gradient;

                if (getModel().isPressed()) {
                    gradient = new GradientPaint(0, 0, pressTop, 0, getHeight(), pressBottom);
                } else if (getModel().isRollover()) {
                    gradient = new GradientPaint(0, 0, hoverTop, 0, getHeight(), hoverBottom);
                } else {
                    gradient = new GradientPaint(0, 0, normalTop, 0, getHeight(), normalBottom);
                }

                g2.setPaint(gradient);

                // Bentuk oval panjang (pill button)
                int arc = getHeight(); // supaya ujungnya bulat penuh
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), arc, arc);

                super.paintComponent(g);
                g2.dispose();
            }
        };
        cancelBtn = new javax.swing.JButton() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();

                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // Warna dasar [200,50,50]
                Color normalTop = new Color(200, 50, 50);
                Color normalBottom = new Color(170, 40, 40);

                // Hover → lebih terang
                Color hoverTop = new Color(220, 70, 70);
                Color hoverBottom = new Color(190, 60, 60);

                // Pressed → lebih gelap
                Color pressTop = new Color(150, 30, 30);
                Color pressBottom = new Color(120, 25, 25);

                GradientPaint gradient;

                if (getModel().isPressed()) {
                    gradient = new GradientPaint(0, 0, pressTop, 0, getHeight(), pressBottom);
                } else if (getModel().isRollover()) {
                    gradient = new GradientPaint(0, 0, hoverTop, 0, getHeight(), hoverBottom);
                } else {
                    gradient = new GradientPaint(0, 0, normalTop, 0, getHeight(), normalBottom);
                }

                g2.setPaint(gradient);

                int arc = getHeight(); // Rounded corner
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), arc, arc);

                super.paintComponent(g);
                g2.dispose();
            }
        };
        resetStatusLabel = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(186, 238, 218));

        resetPasswordLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        resetPasswordLabel.setForeground(new java.awt.Color(0, 102, 102));
        resetPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resetPasswordLabel.setText("Reset password");

        jLabel2.setText("Email");

        resetBtn.setForeground(new java.awt.Color(222, 224, 237));
        resetBtn.setText("Send");
        resetBtn.setBorderPainted(false);
        resetBtn.setContentAreaFilled(false);
        resetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        resetBtn.setOpaque(false);
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        cancelBtn.setForeground(new java.awt.Color(222, 224, 237));
        cancelBtn.setText("Cancel");
        cancelBtn.setBorderPainted(false);
        cancelBtn.setContentAreaFilled(false);
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cancelBtn.setOpaque(false);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        resetStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resetStatusLabel.setText("Click send button to send reset password link");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetStatusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(emailTxt)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(resetPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resetPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(resetBtn))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        emailText = emailTxt.getText();
        
        if (ValidationUtils.isEmpty(emailText)) {
            JOptionPane.showMessageDialog(this, "Please fill the email fields", "Email is empty", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!ValidationUtils.isValidEmail(emailText)) {
            JOptionPane.showMessageDialog(this, "Please type the email correctly", "Email is not valid", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        setLoading(true);
        
        SwingWorker<Void, Void> worker = new SwingWorker<Void,Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                authService.sendPasswordResetEmail(emailText);
                return null;
            }
            @Override
            protected void done() {
                try {
                    get();
                    JOptionPane.showMessageDialog(ResetPasswordDialog.this, "<html>Link password has been send to your email (in inbox or spam folder).<br>If your account is registered, the link to reset your password will arrived on your email.</html>", "Success", JOptionPane.INFORMATION_MESSAGE);
                    ResetPasswordDialog.this.dispose();
                } catch (Exception e) {
                    Throwable cause = e.getCause();
                    String errorMsg = (cause != null) ? cause.getMessage() : e.getMessage();
                    if ("EMAIL_NOT_FOUND".equals(errorMsg)) {
                        JOptionPane.showMessageDialog(ResetPasswordDialog.this, "Email is not registered.", "Email is not valid", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(ResetPasswordDialog.this, "Error: " + errorMsg , "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } finally {
                    setLoading(false);
                }
            }
        };
        worker.execute();
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ResetPasswordDialog dialog = new ResetPasswordDialog(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel resetPasswordLabel;
    private javax.swing.JLabel resetStatusLabel;
    // End of variables declaration//GEN-END:variables
}
